### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by VergeDX** [thehappydinoa/TP-Link-defaults#1]
`````python
vanilla@localhost:~/TP-Link-defaults$ python -V
Python 2.7.13
vanilla@localhost:~/TP-Link-defaults$ python scan.py
  File "scan.py", line 46
    print(f"\nSSID: {ssid} \nMac Address: {mac_address}")
                                                       ^
SyntaxError: invalid syntax
`````

**Comment by thehappydinoa** [comment]
Try running with Python 3

**Comment by VergeDX** [comment]
`````python
vanilla@localhost:~/TP-Link-defaults$ python3.5 -V
Python 3.5.3
vanilla@localhost:~/TP-Link-defaults$ python3.5 scan.py
  File "scan.py", line 46
    print(f"\nSSID: {ssid} \nMac Address: {mac_address}")
                                                       ^
SyntaxError: invalid syntax
`````

**Comment by VergeDX** [comment]
QAQ

**Comment by thehappydinoa** [comment]
I will remove [f strings](https://www.python.org/dev/peps/pep-0498/) as they only work ing 3.6 and above.

**Comment by VergeDX** [comment]
I will compile python3.7 and try again.
Thank you :heart:

**Comment by thehappydinoa** [comment]
Always, best of luck

**Comment by VergeDX** [comment]
`````python
vanilla@localhost:~/git/TP-Link-defaults$ python3.6 -V
Python 3.6.5
vanilla@localhost:~/git/TP-Link-defaults$ python3 scan.py 
Scanning for 30sec...
Traceback (most recent call last):
  File "scan.py", line 84, in <module>
    main()
  File "scan.py", line 73, in main
    monitor=True, timeout=CONFIG.timeout)
  File "/usr/local/lib/python3.6/dist-packages/scapy/sendrecv.py", line 731, in sniff
    *arg, **karg)] = iface
TypeError: __init__() got an unexpected keyword argument 'monitor'
`````

**Comment by VergeDX** [comment]
@thehappydinoa

**Comment by thehappydinoa** [comment]
Fixed in fb6be25

**Comment by thehappydinoa** [comment]
> ```python
> TypeError: __init__() got an unexpected keyword argument 'monitor'
> ```

This issue is bc you didn't install the most recent version of scapy

**Comment by VergeDX** [comment]
`````shell
vanilla@localhost:~/git/TP-Link-defaults$ python3.6 scan.py 
Scanning...
Traceback (most recent call last):
  File "scan.py", line 88, in <module>
    main()
  File "scan.py", line 75, in main
    monitor=True, timeout=CONFIG.timeout)
  File "/usr/local/lib/python3.6/dist-packages/scapy/sendrecv.py", line 731, in sniff
    *arg, **karg)] = iface
TypeError: __init__() got an unexpected keyword argument 'monitor'
`````

**Comment by VergeDX** [comment]
@thehappydinoa

**Comment by thehappydinoa** [comment]
You need to update scapy

**Comment by VergeDX** [comment]
`````python
vanilla@localhost:~/git/TP-Link-defaults$ python3.6 scan.py 
Scanning...
Traceback (most recent call last):
  File "scan.py", line 88, in <module>
    main()
  File "scan.py", line 75, in main
    monitor=True, timeout=CONFIG.timeout)
  File "/usr/local/lib/python3.6/dist-packages/scapy/sendrecv.py", line 836, in sniff
    *arg, **karg)] = iface
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/linux.py", line 443, in __init__
    if not set_iface_monitor(iface, monitor):
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/linux.py", line 407, in set_iface_monitor
    mode = get_iface_mode(iface)
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/linux.py", line 392, in get_iface_mode
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Exception ignored in: <bound method SuperSocket.__del__ of <scapy.arch.linux.L2ListenSocket object at 0xb637c890>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scapy/supersocket.py", line 123, in __del__
    self.close()
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/linux.py", line 481, in close
    set_promisc(self.ins, self.iface, 0)
AttributeError: 'L2ListenSocket' object has no attribute 'ins'
`````

**Comment by VergeDX** [comment]
@thehappydinoa

**Comment by thehappydinoa** [comment]
Please see https://github.com/secdev/scapy/issues/1868
